### ISSUE TITLE
signed assembly

### ISSUE THREAD

**Issue by kaink4** [IharYakimush/solr-net-linq#5]
It is any reason why assembly is signed?

**Comment by IharYakimush** [comment]
signed assembly can be referenced by both signed and unsigned, so everyone can use it.

**Comment by kaink4** [comment]
I understand, but I will explain you a scenario, when this is a problem. I was trying to use your library in app where simple injector is used as a DI. So to proper register SolrNet I need SimpleInjector.SolrNet package which have dependency - SolrNet. The problem: Nuget will download not signed version of SolrNet which causing your library to exception in runtime because it expect signed SolrNet... By the way - your library is great:) Long story short - can't use your library in pair with SimpleInjector.SolrNet or other lib which depends on SolrNet.

**Comment by IharYakimush** [comment]
SolrNet.Linq reference unsigned version of SolrNet (SolrNet, Version=0.9.1.0, Culture=neutral, PublicKeyToken=null). I am not sure that signed version of SolrNet exists.

Could you please provide exception that you faced and sample project to reproduce the issue ?

**Comment by IharYakimush** [comment]
Taking into account that SolrNet is unsigned it is really make no sense to sign SolrNet.Linq, so this is fixed in version 2.0.0
