### ISSUE TITLE
AsQueryable outputs exception when upgrading SolrNet to 1.1.1

### ISSUE THREAD

**Issue by KyleBorg10** [IharYakimush/solr-net-linq#8]
Hi,

I am making use of Solrnet with Solrnet.Linq. Right now I am in the process of migrating from .net6 to .net7 and upgrading NuGet packages as well. When I'm upgrading the Solrnet package to 1.1.1, I am getting the following exception when I try to perform .Count() on IQueryable object.

`System.MissingMethodException: 'Method not found: 'Int32 SolrNet.Impl.AbstractSolrQueryResults1.get_NumFound()'.'`

Are there any fixes for this please?

**Comment by IharYakimush** [comment]
Hi @KyleBorg10, try version 2.111.3

**Comment by KyleBorg10** [comment]
Hi @IharYakimush,

Thank you very much for the quick fix :) Works very well. Appreciate it
